spring:
  datasource:
    url: jdbc:mysql://192.168.10.10/zhenfuli?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  application:
    name:  foreign01
  scan:
    base-packages: org.cc.service
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:2181
server:
  port: 8889