spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ds0?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 14/2
    driver-class-name: com.mysql.cj.jdbc.Driver