spring:
  application:
    name: foreign-client
dubbo:
  application:
    name:  foreign-client
  registry:
    address: zookeeper://127.0.0.1:2181
server:
  port: 8887
logging:
  level:
    root: debug