dataSources:
  ds0:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds0?characterEncoding=utf8&useSSL=false
    username: root
    password: 14/2
  ds1:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds1?characterEncoding=utf8&useSSL=false
    username: root
    password: 14/2
shardingRule:
  tables:
    t_store_order:
      actualDataNodes: ds$->{0..1}.t_store_order$->{0..1}

      databaseStrategy:
        inline:
          shardingColumn: store_order_id
          algorithmInlineExpression: t_store_order$->{store_order_id % 2}
      tableStrategy:
        inline:
          shardingColumn: store_order_id
          algorithmInlineExpression: t_store_order$->{store_order_id % 2}
      keyGenerator:
        column: store_order_id
        type: SNOWFLAKE
        props:
          worker.id: 2
          max.tolerate.time.difference.milliseconds: 3